"""empty message

Revision ID: 278504658a31
Revises: 
Create Date: 2021-05-12 16:59:38.008273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278504658a31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('areas_de_programacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('preguntas_frecuentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=500), nullable=False),
    sa.Column('respuesta', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pregunta')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('roles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('apellido', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.String(length=600), nullable=True),
    sa.Column('linkedin', sa.String(length=150), nullable=True),
    sa.Column('genero', sa.String(length=600), nullable=True),
    sa.Column('github', sa.String(length=600), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comandos_terminal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comando_nombre', sa.String(length=500), nullable=False),
    sa.Column('comando_contenido', sa.String(length=900), nullable=False),
    sa.Column('comando_fecha', sa.String(length=20), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foro_nombre', sa.String(length=500), nullable=False),
    sa.Column('foro_contenido', sa.String(length=900), nullable=False),
    sa.Column('foro_fecha', sa.String(length=20), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foro_contenido'),
    sa.UniqueConstraint('foro_nombre')
    )
    op.create_table('lenguajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lenguaje_nombre', sa.String(length=500), nullable=False),
    sa.Column('lenguaje_descripcion', sa.String(length=900), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lenguaje_nombre')
    )
    op.create_table('plantillas_codigo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_nombre', sa.String(length=500), nullable=False),
    sa.Column('plantilla_contenido', sa.String(length=900), nullable=False),
    sa.Column('plantilla_fecha', sa.String(length=20), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_contenido', sa.String(length=900), nullable=False),
    sa.Column('post_fecha', sa.String(length=20), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_contenido')
    )
    op.create_table('foro_comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario_fecha', sa.String(length=20), nullable=False),
    sa.Column('comentario_contenido', sa.String(length=900), nullable=False),
    sa.Column('foros_id', sa.Integer(), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foros_id'], ['foros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comentario_contenido')
    )
    op.create_table('post_comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario_fecha', sa.String(length=20), nullable=False),
    sa.Column('comentario_contenido', sa.String(length=900), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comentario_contenido')
    )
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_likes')
    op.drop_table('post_comentarios')
    op.drop_table('foro_comentarios')
    op.drop_table('posts')
    op.drop_table('plantillas_codigo')
    op.drop_table('lenguajes')
    op.drop_table('foros')
    op.drop_table('comandos_terminal')
    op.drop_table('perfiles')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('preguntas_frecuentes')
    op.drop_table('areas_de_programacion')
    op.drop_table('academias')
    # ### end Alembic commands ###
