"""empty message

Revision ID: 7996dfae0e79
Revises: fd2dac3dadff
Create Date: 2021-05-06 11:19:28.710552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7996dfae0e79'
down_revision = 'fd2dac3dadff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comandos_terminal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comando_nombre', sa.String(length=500), nullable=False),
    sa.Column('comando_contenido', sa.String(length=900), nullable=False),
    sa.Column('comando_fecha', sa.String(length=20), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foro_nombre', sa.String(length=500), nullable=False),
    sa.Column('foro_contenido', sa.String(length=900), nullable=False),
    sa.Column('foro_fecha', sa.String(length=20), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lenguajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lenguaje_nombre', sa.String(length=500), nullable=False),
    sa.Column('lenguaje_descripcion', sa.String(length=900), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantillas_codigo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_nombre', sa.String(length=500), nullable=False),
    sa.Column('plantilla_contenido', sa.String(length=900), nullable=False),
    sa.Column('plantilla_fecha', sa.String(length=20), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_contenido', sa.String(length=900), nullable=False),
    sa.Column('post_fecha', sa.String(length=20), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foro_comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario_fecha', sa.String(length=20), nullable=False),
    sa.Column('comentario_contenido', sa.String(length=900), nullable=False),
    sa.Column('foros_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foros_id'], ['foros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario_fecha', sa.String(length=20), nullable=False),
    sa.Column('comentario_contenido', sa.String(length=900), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.Column('perfiles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfiles_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_likes')
    op.drop_table('post_comentarios')
    op.drop_table('foro_comentarios')
    op.drop_table('posts')
    op.drop_table('plantillas_codigo')
    op.drop_table('lenguajes')
    op.drop_table('foros')
    op.drop_table('comandos_terminal')
    # ### end Alembic commands ###
